version: '3'

services:
  bot:
    image: kylmakalle/Telescopy:latest
    restart: always
    container_name: tgvkbot
    logging:
      options:
        max-size: "10M"
        max-file: "10"
    restart: always
    env_file: .env
    labels:
      com.centurylinklabs.watchtower.enable: 'true'
